name: flutter_mongodb_mobile
description: A new flutter plugin project.
version: 0.0.1
author: Minsu Lee <amond@amond.netm>
homepage: https://github.com/amondnet/flutter_mongodb_mobile

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.2+1
  mongo_dart: ^0.3.5
  bson: ^0.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.example.mongodb_mobile
    pluginClass: MongodbMobilePlugin
